spring:
    application:
        name: Cowing-msa-trading

#    config:
#        activate:
#            on-profile: local

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PWD}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    data:
        redis:
            host: localhost
            port: 6379