#spring:
#  application:
#    name: Cowing-msa-trading
#
#  config:
#    activate:
#      on-profile: prod
#
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PWD}
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        ddl-auto: update
#        dialect: org.hibernate.dialect.MariaDBDialect
#
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}